### POST /api/check
POST http://localhost:8080/api/check
Content-Type: application/json

{
    "flightNumber": "12345",
    "date": "2025-07-12"
}

### POST /api/generate
POST http://localhost:8080/api/generate
Content-Type: application/json

{
    "name": "John Doe",
    "id": "123456789",
    "flightNumber": "12345",
    "date": "2025-07-12",
    "aircraft": "ATR"
}